version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  jobs:
    build:
      html:
        - pip install -r requirements-rtd.txt
        - pip install .
        - zensical build
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/
      - cp --recursive site/* $READTHEDOCS_OUTPUT/html/
