version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  jobs:
    build:
      html:
        - zensical build
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/
      - cp --recursive site/* $READTHEDOCS_OUTPUT/html/

python:
  install:
    - requirements: requirements-rtd.txt
    - method: pip
      path: .
